[workspace]
authors = ["Su Hang <suhang@shanghaitech.edu.cn>"]
channels = ["conda-forge", "robostack-noetic"]
name = "event simulator"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cd ~/esim_ws && catkin build rpg_esim"

[dependencies]
vcstool = "*"
cmake = "3.*"
python = "*"
glfw = "*"
glm = "*"
opencv = "*"
libcaer = "*"
glog = "0.6.*"
wheel = "*"
glew = "*"
catkin_tools = "*"
ros-noetic-ros = "*"
ros-noetic-roslaunch = "*"
ros-noetic-pcl-ros = "*"
ros-noetic-image-transport = "*"
ros-noetic-camera-info-manager = "*"
ros-noetic-cv-bridge = "*"
ros-noetic-eigen-conversions = "*"
ros-noetic-tf-conversions = "*"
yaml-cpp = "*"
libxkbcommon = "*"
ros-noetic-visualization-msgs = "*"
ros-noetic-rviz = "*"
